services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Admin Controllers
    baihu.admin_controller:
        class: baihu\baihu\src\controller\admin\index_controller
        calls:
            - [set_container, ['@Psr\Container\ContainerInterface']]
        tags: ['container.service_subscriber']

    # ganstaz.gzo.admin.settings_controller:
    #     class: ganstaz\gzo\src\controller\admin\settings_controller
    #     autowire: true
    #     arguments:
    #         - '@ganstaz.gzo.settings'
    #     calls:
    #         - [set_container, ['@Psr\Container\ContainerInterface']]
    #     tags: ['container.service_subscriber']
