services:
    phpbb\auth\auth: '@auth'
    phpbb\avatar\helper: '@avatar.helper'
    phpbb\cache\driver\driver_interface: '@cache.driver'
    phpbb\config\config: '@config'
    phpbb\cron\manager: '@cron.manager'
    phpbb\db\driver\driver_interface: '@dbal.conn'
    phpbb\event\dispatcher: '@event_dispatcher'
    phpbb\group\helper: '@group_helper'
    phpbb\language\language: '@language'
    phpbb\pagination: '@pagination'
    phpbb\request\request: '@request'
    phpbb\request\request_interface: '@request'
    phpbb\routing\helper: '@routing.helper'
    phpbb\symfony_request: '@symfony_request'
    # phpbb\template\context: '@template_context'
    phpbb\template\template: '@template'
    # phpbb\template\twig\environment: '@template.twig.environment'
    # phpbb\textformatter\s9e\renderer: '@text_formatter.s9e.renderer'
    phpbb\user: '@user'
