areaz_main:
    path: /index
    controller: baihu.admin_controller:index

areaz_settings:
    path: /area-settings
    controller: baihu.admin_controller:index
areaz_pages:
    path: /area-pages
    controller: baihu.admin_controller:index

areaz_plugins:
    path: /area-plugins
    controller: baihu.admin_controller:index
