services:
    _defaults:
        autowire: true
        autoconfigure: true

    baihu.auth:
        class: baihu\baihu\src\security\authorization

    baihu\baihu\src\security\authorization: '@baihu.auth'

    baihu.auth_kernel_subscriber:
        class: baihu\baihu\src\security\event\auth_kernel_subscriber
        tags:
            - { name: kernel.event_subscriber }
