baihu_area_routing:
    resource: area_routes.yml
    prefix: /admin

# Redirect to admin main (legacy)
baihu_admin_redirect:
    path: /admin/main
    controller: baihu.admin_redirect:index

# Main page
baihu_main_index:
    path: /
    controller: baihu.index_controller:index

# Articles
baihu_articles:
    path: /articles/{fid}
    controller: baihu.posts_redirect_controller:articles
    requirements:
        id: \d+

# Redirect to topic page
baihu_article:
    path: /article/{aid}
    controller: baihu.posts_redirect_controller:article
    requirements:
        aid: \d+

# Redirect to recent post
baihu_recent_post:
    path: /recent-post/aid-{aid}-p-{post_id}
    controller: baihu.posts_redirect_controller:recent_post
    requirements:
        aid: \d+
        post_id: \d+

# Redirect to recent topic
baihu_recent_topic:
    path: /recent-article/{aid}
    controller: baihu.posts_redirect_controller:recent_topic
    requirements:
        aid: \d+

# Members
baihu_member:
    path: /u/{username}
    controller: baihu.profile_controller:index
    defaults:
        tab: profile

baihu_member_tab:
    path: /u/{username}/tab/{tab}
    controller: baihu.profile_controller:index

baihu_members_redirect:
    path: /members
    controller: baihu.members.redirect_controller:index
