baihu_area_routing:
    resource: area_routes.yml
    prefix: /admin

# Redirect to admin main (legacy)
baihu_admin_redirect:
    path: /admin/main
    controller: baihu.admin_redirect:index

# Main page
baihu_main_index:
    path: /
    controller: baihu.index_controller:index

# Articles
baihu_articles:
    path: /articles/{fid}
    controller: baihu.posts_redirect_controller:articles
    requirements:
        id: \d+

# Redirect to topic page
baihu_article:
    path: /article/{aid}
    controller: baihu.posts_redirect_controller:article
    requirements:
        aid: \d+

# Redirect to forum page
baihu_post_create:
    path: /create-post/{fid}
    controller: baihu.posts_redirect_controller:post
    requirements:
        fid: \d+

# Redirect to recent post
baihu_recent_post:
    path: /recent-post/aid-{aid}-p-{post_id}
    controller: baihu.posts_redirect_controller:recent_post
    requirements:
        aid: \d+
        post_id: \d+

# Redirect to recent topic
baihu_recent_topic:
    path: /recent-article/{aid}
    controller: baihu.posts_redirect_controller:recent_topic
    requirements:
        aid: \d+

# Members / Profile
baihu_member:
    path: /u/{username}
    controller: baihu.profile_controller:index
    defaults:
        tid: profile

baihu_member_befriend:
    path: /u/add-friend/{user_id}
    controller: baihu.profile.friend_controller:create
    requirements:
        user_id: \d+

baihu_member_unfriend:
    path: /u/remove-friend/{user_id}
    controller: baihu.profile.friend_controller:delete
    requirements:
        user_id: \d+

baihu_member_blacklist:
    path: /u/blacklist/{user_id}
    controller: baihu.profile.blacklist_controller:create
    requirements:
        user_id: \d+

baihu_member_unblacklist:
    path: /u/unblacklist/{user_id}
    controller: baihu.profile.blacklist_controller:delete
    requirements:
        user_id: \d+

baihu_profile_tab:
    path: /u/{username}/tab-{tid}
    controller: baihu.profile_controller:index

# Redirect to memberlist (legacy)
baihu_members_redirect:
    path: /members
    controller: baihu.members.redirect_controller:index
