imports:
    - { resource: alias.yml }
    - { resource: area.yml }
    - { resource: auth.yml }
    - { resource: controller.yml }
    - { resource: plugins.yml }
    - { resource: profile.yml }
    - { resource: tables.yml }
    - { resource: twig.yml }
    - { resource: user.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    baihu.subscribers:
        class: baihu\baihu\src\event\subscribers
        tags:
            - { name: event.listener }

    baihu.entity.manager:
        class: baihu\baihu\src\db\manager

    baihu\baihu\src\db\manager: '@baihu.entity.manager'
