services:
    _defaults:
        autowire: true
        autoconfigure: true

    baihu.create:
        class: baihu\baihu\src\user\create

    baihu.page:
        class: baihu\baihu\src\user\page
        autowire: false
        arguments:
            - '@config'
            - '@user'
            - '%core.php_ext%'

    baihu.time:
        class: baihu\baihu\src\user\time

    baihu.users_loader:
        class: baihu\baihu\src\user\loader
        autowire: false
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.users%'

    baihu\baihu\src\user\create: '@baihu.create'
    baihu\baihu\src\user\page: '@baihu.page'
    baihu\baihu\src\user\loader: '@baihu.users_loader'
    baihu\baihu\src\user\time: '@baihu.time'
