name: Tests

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main

jobs:
    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@master
        with:
            EXTNAME: baihu/baihu # Your extension vendor/package name
            EPV: 0
            RUN_MYSQL_JOBS: 0
            RUN_PGSQL_JOBS: 0
            RUN_MSSQL_JOBS: 0
            RUN_WINDOWS_JOBS: 0
            RUN_FUNCTIONAL_TESTS: 0
            PRIMARY_PHP_VERSION: '8.2'
            PHP_VERSION_MATRIX: '["8.2", "8.3", "8.4", "8.5"]'
